export const INDIAN_STATES_AND_UNION_TERRITORIES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
] as const

export const VOLUNTEER_ROLES = [
  {
    value: 'teacher',
    label: 'Teaching students',
    description: 'Join our team of volunteers who teach students at underprivileged schools.',
    requirements: 'Basic knowledge of physics and particle physics.',
  },
  {
    value: 'content-building',
    label: 'Content building',
    description: 'Help us build more resources, tools and content to enhance our programmes.',
    requirements: 'Basic knowledge of physics, as well as coding or design.',
  },
  {
    value: 'social-media',
    label: 'Social media',
    description: 'Help spread the word and increase our impact.',
    requirements: 'Expertise in social media, either in ideation, filming or editing.',
  },
] as const

export type VolunteerRole = typeof VOLUNTEER_ROLES[number]['value']
